Repository Taboms/myhands-aos, pull requests merged in 2025-01, with the labels that each got.

#7 [FEAT] Zustand 설치 및 적용
  myhands/.eslintrc.js
  myhands/App.tsx
  myhands/package-lock.json
  myhands/package.json
  myhands/src/api/auth.ts
  myhands/src/api/axios.ts
  myhands/src/api/queryClient.ts
  myhands/src/assets/logo/logo-circle.png
  myhands/src/components/CustomButton.tsx
  myhands/src/components/InputField.tsx
  myhands/src/components/LoadingScreen.tsx
  myhands/src/constants/keys.ts
  myhands/src/constants/numbers.ts
  myhands/src/hooks/queries/useAuth.ts
  myhands/src/hooks/useForm.ts
  myhands/src/navigations/drawer/AdminDrawerNavigator.tsx
  myhands/src/navigations/drawer/CustomUserDrawerContent.style.ts
  myhands/src/navigations/drawer/CustomUserDrawerContent.tsx
  myhands/src/navigations/drawer/UserDrawerNavigator.tsx
  myhands/src/navigations/root/RootNavigator.tsx
  myhands/src/navigations/stack/LoggedOutStackNavigator.tsx
  myhands/src/screens/auth/LoginScreen.tsx
  myhands/src/screens/mypage/MypageHomeScreen.tsx
  myhands/src/screens/quest/QuestCalendarScreen.tsx
  myhands/src/screens/quest/QuestStatusScreen.tsx
  myhands/src/store/authStore.ts
  myhands/src/store/store.ts
  myhands/src/store/userStore.ts
  myhands/src/types/domain.ts
  myhands/src/utils/asyncStorage.ts
  myhands/src/utils/encryptStorage.ts
  myhands/src/utils/index.ts
  myhands/src/utils/validate.ts
  myhands/tsconfig.json
Labels: Complete, FrontEnd

#11 [BOARD] 게시판 화면 구현
  myhands/package.json
  myhands/src/api/boardApi.ts
  myhands/src/assets/image/board-ellipse.png
  myhands/src/assets/logo/logo-row.png
  myhands/src/components/board/BoardItem.tsx
  myhands/src/components/board/BoardList.tsx
  myhands/src/components/board/Header.tsx
  myhands/src/components/board/SearchBar.tsx
  myhands/src/constants/navigations.ts
  myhands/src/navigations/stack/LoggedInStackNavigator.tsx
  myhands/src/screens/board/BoardAllScreen.tsx
  myhands/src/screens/board/BoardDetailScreen.tsx
  myhands/src/screens/board/BoardHomeScreen.tsx
Labels: Complete, FrontEnd

#13 [FEAT] 차트 패키지 추가 및 구현, 커스텀 모달 구현
  myhands/package-lock.json
  myhands/package.json
  myhands/src/api/queryClient.ts
  myhands/src/assets/icons/logout2.svg
  myhands/src/assets/icons/modalIcons.tsx
  myhands/src/components/_modal/CustomModal.style.ts
  myhands/src/components/_modal/CustomModal.tsx
  myhands/src/components/_modal/modalConstants.ts
  myhands/src/components/quest/ExpHistory.tsx
  myhands/src/components/quest/QuestChallenge.style.ts
  myhands/src/components/quest/QuestChallenge.tsx
  myhands/src/components/quest/QuestRecord.tsx
  myhands/src/components/quest/WeekRecord.tsx
  myhands/src/components/quest/WeeklyTimeline.tsx
  myhands/src/constants/colors.ts
  myhands/src/constants/index.ts
  myhands/src/navigations/drawer/UserDrawerNavigator.tsx
  myhands/src/screens/quest/QuestHomeScreen.tsx
  myhands/src/screens/quest/QuestStatusScreen.style.ts
  myhands/src/screens/race/RaceHomeScren.tsx
  myhands/src/utils/calculateWeeks.ts
  myhands/src/utils/index.ts
Labels: Complete, FrontEnd

#15 [AUTH] 로그인, 비밀번호 수정
  myhands/src/api/auth.ts
  myhands/src/api/setting.ts
  myhands/src/components/InputField.tsx
  myhands/src/components/_modal/modalConstants.ts
  myhands/src/components/changePassword/Condition.tsx
  myhands/src/components/changePassword/ErrorMessage.tsx
  myhands/src/components/changePassword/HeaderButton.tsx
  myhands/src/components/changePassword/PasswordInput.tsx
  myhands/src/components/login/Header.tsx
  myhands/src/components/login/LoginButton.tsx
  myhands/src/components/login/LoginInput.tsx
  myhands/src/constants/keys.ts
  myhands/src/screens/auth/LoginScreen.tsx
  myhands/src/screens/board/BoardHomeScreen.tsx
  myhands/src/screens/settings/ChangePasswordScreen.tsx
  myhands/src/store/authStore.ts
Labels: FrontEnd, Asking For Review

#22 [QUEST] 퀘스트 화면 구현 및 폰트 적용
  myhands/App.tsx
  myhands/android/app/build.gradle
  myhands/android/app/google-services.json
  myhands/android/app/src/main/AndroidManifest.xml
  myhands/android/app/src/main/assets/fonts/Pretendard-Black.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-Bold.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-ExtraBold.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-ExtraLight.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-Light.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-Medium.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-Regular.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-SemiBold.ttf
  myhands/android/app/src/main/assets/fonts/Pretendard-Thin.ttf
  myhands/android/app/src/main/res/drawable/ic_notification.png
  myhands/android/build.gradle
  myhands/android/link-assets-manifest.json
  myhands/index.js
  myhands/ios/link-assets-manifest.json
  myhands/ios/myhands.xcodeproj/project.pbxproj
  myhands/ios/myhands/Info.plist
  myhands/package-lock.json
  myhands/package.json
  myhands/react-native.config.js
  myhands/src/api/auth.ts
  myhands/src/api/quest.ts
  myhands/src/assets/fonts/Pretendard-Black.ttf
  myhands/src/assets/fonts/Pretendard-Bold.ttf
  myhands/src/assets/fonts/Pretendard-ExtraBold.ttf
  myhands/src/assets/fonts/Pretendard-ExtraLight.ttf
  myhands/src/assets/fonts/Pretendard-Light.ttf
  myhands/src/assets/fonts/Pretendard-Medium.ttf
  myhands/src/assets/fonts/Pretendard-Regular.ttf
  myhands/src/assets/fonts/Pretendard-SemiBold.ttf
  myhands/src/assets/fonts/Pretendard-Thin.ttf
  myhands/src/components/quest/QuestRecord.tsx
  myhands/src/components/styles/CustomTextBold.tsx
  myhands/src/components/styles/CustomTextMedium.tsx
  myhands/src/components/styles/CustomTextRegular.tsx
  myhands/src/components/styles/CustomTextSemoBold.tsx
  myhands/src/constants/colors.ts
  myhands/src/hooks/useNotification/NotificationProvider.tsx
  myhands/src/hooks/useNotification/index.ts
  myhands/src/navigations/stack/LoggedInStackNavigator.tsx
  myhands/src/screens/notifications/InAppNotification.tsx
  myhands/src/screens/notifications/NotificationsScreen.tsx
  myhands/src/screens/quest/QuestCalendarScreen.tsx
  myhands/src/screens/quest/QuestHomeScreen.tsx
  myhands/src/store/authStore.ts
  myhands/src/types/domain.ts
  myhands/src/utils/pushNoti.js
  myhands/src/utils/quest.ts
  myhands/tsconfig.json
Labels: Complete, FrontEnd

#23 [FIX] fcm 토큰 세팅, 어드민 드로어 수정
  myhands/src/components/quest/QuestRecord.tsx
  myhands/src/navigations/drawer/AdminDrawerNavigator.tsx
  myhands/src/screens/auth/LoginScreen.tsx
Labels: FrontEnd, Asking For Review

#25 [DESIGN] 폰트 적용
  myhands/src/components/board/BoardItem.tsx
  myhands/src/components/board/BoardList.tsx
  myhands/src/components/board/Header.tsx
  myhands/src/components/board/SearchBar.tsx
  myhands/src/components/changePassword/Condition.tsx
  myhands/src/components/changePassword/ErrorMessage.tsx
  myhands/src/components/changePassword/HeaderButton.tsx
  myhands/src/components/changePassword/PasswordInput.tsx
  myhands/src/components/changeProfile/ProfileInfo.tsx
  myhands/src/components/changeProfile/styles.ts
  myhands/src/components/login/LoginButton.tsx
  myhands/src/components/login/LoginInput.tsx
  myhands/src/components/styles/CustomTextSemiBold.tsx
  myhands/src/screens/auth/LoginScreen.tsx
  myhands/src/screens/board/BoardDetailScreen.tsx
  myhands/src/screens/settings/ChangePasswordScreen.tsx
Labels: Complete, FrontEnd

#27 [ADMIN] 관리자 메인, 회원 생성 페이지 구현
  myhands/package-lock.json
  myhands/package.json
  myhands/src/api/auth.ts
  myhands/src/assets/image/search-board.png
  myhands/src/assets/image/sing-up.png
  myhands/src/assets/image/user-list.png
  myhands/src/assets/image/warning.png
  myhands/src/assets/image/write-board.png
  myhands/src/components/_modal/modalConstants.ts
  myhands/src/constants/department.ts
  myhands/src/navigations/drawer/AdminDrawerNavigator.tsx
  myhands/src/navigations/stack/AdminStackNavigator.tsx
  myhands/src/screens/admin/AdminHomeScreen.tsx
  myhands/src/screens/admin/AdminSignupScreen.tsx
Labels: Complete, FrontEnd

#30 [BOARD] 게시판 UI 수정
  myhands/src/components/board/BoardItem.tsx
  myhands/src/screens/board/BoardAllScreen.tsx
Labels: Complete, FrontEnd

#34 [EXP] 경험치 목록 화면 구현
  myhands/src/api/mypage.ts
  myhands/src/components/exp/ExpItem.tsx
  myhands/src/components/exp/Label.tsx
  myhands/src/constants/colors.ts
  myhands/src/screens/mypage/ExpAllScreen.tsx
Labels: Complete, FrontEnd

#35 [FEAT] 알림 api 연결 및 랭킹 타이머 구현
  myhands/App.tsx
  myhands/package-lock.json
  myhands/package.json
  myhands/src/api/notification.ts
  myhands/src/api/quest.ts
  myhands/src/assets/character/character7.png
  myhands/src/assets/icons/notiIcons.tsx
  myhands/src/components/quest/WeeklyTimeline.tsx
  myhands/src/constants/bottomTabs.ts
  myhands/src/navigations/bottomTabs/BottomTabsNavigator.tsx
  myhands/src/screens/notifications/NotificationsScreen.tsx
  myhands/src/screens/quest/QuestCalendarScreen.tsx
  myhands/src/screens/quest/QuestStatusScreen.tsx
  myhands/src/screens/race/RaceHomeScreen.tsx
  myhands/src/screens/race/RaceHomeScren.tsx
  myhands/src/store/authStore.ts
  myhands/src/store/notificationStore.ts
  myhands/src/store/questStore.ts
  myhands/src/types/domain.ts
  myhands/src/utils/quest.ts
Labels: Complete, FrontEnd

#39 [RANKING] 팀 랭킹 화면 구현
  myhands/src/api/ranking.ts
  myhands/src/assets/icons/departmentIcons.tsx
  myhands/src/assets/icons/rankingIcons.png
  myhands/src/assets/image/first.png
  myhands/src/assets/image/second.png
  myhands/src/assets/image/third.png
  myhands/src/components/ranking/MyTeamInfo.tsx
  myhands/src/components/ranking/RankingItem.tsx
  myhands/src/components/ranking/TeamRanking.tsx
  myhands/src/constants/ranking.ts
  myhands/src/screens/race/RaceHomeScreen.tsx
Labels: Complete, FrontEnd

#40 [STYLE] 랭킹, 어드민 스타일 수정
  myhands/src/components/board/BoardList.tsx
  myhands/src/components/board/Header.tsx
  myhands/src/components/changePassword/HeaderButton.tsx
  myhands/src/components/changeProfile/ProfileInfo.tsx
  myhands/src/components/changeProfile/styles.ts
  myhands/src/components/exp/ExpItem.tsx
  myhands/src/components/login/LoginButton.tsx
  myhands/src/components/login/LoginInput.tsx
  myhands/src/components/mypage/ExperienceStatus.tsx
  myhands/src/components/mypage/Profile.tsx
  myhands/src/components/mypage/ProgressBar.tsx
  myhands/src/components/ranking/RankingItem.tsx
  myhands/src/constants/navigations.ts
  myhands/src/navigations/bottomTabs/BottomTabsNavigator.tsx
  myhands/src/navigations/drawer/CustomUserDrawerContent.tsx
  myhands/src/navigations/drawer/UserDrawerNavigator.tsx
  myhands/src/navigations/stack/AdminStackNavigator.tsx
  myhands/src/screens/admin/AdminHomeScreen.tsx
  myhands/src/screens/admin/AdminPostListScreen.tsx
  myhands/src/screens/admin/AdminUserDetailScreen.tsx
  myhands/src/screens/admin/AdminWritePostScreen.tsx
  myhands/src/screens/auth/LoginScreen.tsx
  myhands/src/screens/board/BoardHomeScreen.tsx
  myhands/src/screens/mypage/ExpAllScreen.tsx
  myhands/src/screens/mypage/MypageHomeScreen.tsx
  myhands/src/screens/race/RaceHomeScreen.tsx
Labels: FrontEnd

#41 [ADMIN] 회원 목록 조회 필터링
  myhands/src/components/admin/AdminUserList.tsx
  myhands/src/screens/admin/AdminUserListScreen.tsx
Labels: Complete, FrontEnd

#43 [SETTING] 앱 설정
  myhands/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  myhands/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  myhands/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  myhands/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  myhands/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  myhands/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  myhands/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  myhands/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  myhands/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  myhands/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  myhands/android/app/src/main/res/values/strings.xml
Labels: Complete, FrontEnd

#44 [FEAT] QA 사항 수정
  myhands/android/app/google-services.json
  myhands/package-lock.json
  myhands/package.json
  myhands/src/api/admin.ts
  myhands/src/api/auth.ts
  myhands/src/api/notification.ts
  myhands/src/assets/icons/adminIcons.tsx
  myhands/src/assets/icons/alertIcons.tsx
  myhands/src/components/CalendarView.tsx
  myhands/src/components/LoadingScreen.tsx
  myhands/src/components/_modal/CustomModal.tsx
  myhands/src/components/_modal/modalConstants.ts
  myhands/src/components/admin/AdminUserList.tsx
  myhands/src/components/login/LoginInput.tsx
  myhands/src/components/mypage/Profile.tsx
  myhands/src/components/quest/questCalendar/QuestCalendarHeader.tsx
  myhands/src/components/quest/questCalendar/QuestItem.tsx
  myhands/src/components/quest/questCalendar/QuestLegend.tsx
  myhands/src/components/quest/questCalendar/WeekQuest.tsx
  myhands/src/components/quest/questStatus/ExpHistory.tsx
  myhands/src/components/quest/questStatus/QuestChallenge.tsx
  myhands/src/components/quest/questStatus/QuestRecord.tsx
  myhands/src/components/quest/questStatus/WeeklyTimeline.tsx
  myhands/src/constants/navigations.ts
  myhands/src/navigations/drawer/AdminDrawerNavigator.tsx
  myhands/src/navigations/drawer/CustomAdminDrawerContent.tsx
  myhands/src/navigations/stack/AdminStackNavigator.tsx
  myhands/src/screens/admin/AdminBoardDetailScreen.tsx
  myhands/src/screens/admin/AdminPostListScreen.tsx
  myhands/src/screens/admin/AdminSignupScreen.tsx
  myhands/src/screens/admin/AdminUserDetailScreen.tsx
  myhands/src/screens/admin/AdminUserListScreen.tsx
  myhands/src/screens/admin/AdminWritePostScreen.tsx
  myhands/src/screens/auth/LoginScreen.tsx
  myhands/src/screens/notifications/NotificationsScreen.tsx
  myhands/src/screens/quest/QuestCalendarScreen.tsx
  myhands/src/screens/quest/QuestHomeScreen.tsx
  myhands/src/screens/quest/QuestStatusScreen.tsx
  myhands/src/screens/race/RaceHomeScreen.tsx
  myhands/src/screens/settings/ChangeProfileScreen.tsx
  myhands/src/store/adminStore.ts
  myhands/src/store/signupStore.ts
  myhands/src/types/types.ts
Labels: FrontEnd

#45 [FEAT] axios 로직 변경
  myhands/src/api/axios.ts
  myhands/src/store/authStore.ts
Labels: Complete, FrontEnd
